kind: pipeline
name: default

steps:
  - name: restore-cache
    image: plugins/s3-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      pull: true
      root:
        from_secret: s3_bucket_name
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      mount:
        - node_modules

  - name: setup
    image: node:carbon
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn
    depends_on:
      - restore-cache

  - name: build
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build:prod
    depends_on:
      - setup

  - name: test
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn test
    depends_on:
      - setup

  - name: compile-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn run tsc
    depends_on:
      - setup

  - name: lint-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-ts
    depends_on:
      - compile-typescript

  - name: lint-less
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-less
    depends_on:
      - setup

  - name: lint-prettier
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-prettier
    depends_on:
      - setup

  - name: rebuild-cache
    image: plugins/s3-cache
    when:
      event: [push, pull_request]
    volumes:
      - name: cache
        path: /cache
    settings:
      pull: true
      root: 
        from_secret: s3_bucket_name
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      rebuild: true
      mount:
        - node_modules
    depends_on: [ lint-prettier, lint-less, lint-typescript, test, build]
     
  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      port: 22
      username: root
      key:
        from_secret: ssh_key
      command_timeout: 600s
      script:
        - /srv/www/owf-staging/deploy.sh
    depends_on:
       - rebuild-cache

volumes:
  - name: cache
    temp: {}
