kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    volumes:
      - name: cache
        path: /cache
      - name: node_modules
        path: ./node_modules
    settings:
      restore: true

  - name: setup
    image: node:carbon
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn

  - name: build
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build:prod

  - name: test
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn test

  - name: compile-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn run tsc

  - name: lint-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-ts

  - name: lint-less
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-less

  - name: lint-prettier
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-prettier

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    volumes:
      - name: cache
        path: /cache
      - name: node_modules
        path: ./node_modules
    settings:
      rebuild: true
     
  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      port: 22
      username: root
      key:
        from_secret: ssh_key
      command_timeout: 600s
      script:
        - /srv/www/owf-staging/deploy.sh

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: node_modules
    temp: {}
