

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - owf

on:
  push:
    branches:
      - feature/cloud

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: yarn
      run: |
        yarn install
        yarn build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'owf'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f11e82e4ca942f3894c21d09ed829ef }}
        package: .
